<script>
(function(a){if("function"===typeof define&&define.amd)define(a);else if("object"===typeof exports)module.exports=a();else{var b=window.Cookies,d=window.Cookies=a();d.noConflict=function(){window.Cookies=b;return d}}})(function(){function a(){for(var a=0,b={};a<arguments.length;a++){var e=arguments[a],f;for(f in e)b[f]=e[f]}return b}function b(d){function c(b,f,h){var l;if("undefined"!==typeof document){if(1<arguments.length){h=a({path:"/"},c.defaults,h);if("number"===typeof h.expires){var g=new Date;
g.setMilliseconds(g.getMilliseconds()+864E5*h.expires);h.expires=g}try{l=JSON.stringify(f),/^[\{\[]/.test(l)&&(f=l)}catch(q){}f=d.write?d.write(f,b):encodeURIComponent(String(f)).replace(/%(23|24|26|2B|3A|3C|3E|3D|2F|3F|40|5B|5D|5E|60|7B|7D|7C)/g,decodeURIComponent);b=encodeURIComponent(String(b));b=b.replace(/%(23|24|26|2B|5E|60|7C)/g,decodeURIComponent);b=b.replace(/[\(\)]/g,escape);return document.cookie=[b,"=",f,h.expires&&"; expires="+h.expires.toUTCString(),h.path&&"; path="+h.path,h.domain&&
"; domain="+h.domain,h.secure?"; secure":""].join("")}b||(l={});for(var g=document.cookie?document.cookie.split("; "):[],m=/(%[0-9A-Z]{2})+/g,p=0;p<g.length;p++){var k=g[p].split("="),n=k[0].replace(m,decodeURIComponent),k=k.slice(1).join("=");'"'===k.charAt(0)&&(k=k.slice(1,-1));try{k=d.read?d.read(k,n):d(k,n)||k.replace(m,decodeURIComponent);if(this.json)try{k=JSON.parse(k)}catch(q){}if(b===n){l=k;break}b||(l[n]=k)}catch(q){}}return l}}c.set=c;c.get=function(a){return c(a)};c.getJSON=function(){return c.apply({json:!0},
[].slice.call(arguments))};c.defaults={};c.remove=function(b,d){c(b,"",a(d,{expires:-1}))};c.withConverter=b;return c}return b(function(){})});
var variables,$,functions={renderObject:function(a,b){var d=variables.context,c=a.appearance?a.appearance:a;c.translate=c.translate||[0,0];c.rotateAdjust=c.rotateAdjust||0;d.translate(c.position[0]+c.translate[0],c.position[1]+c.translate[1]);d.rotate((c.rotate+c.rotateAdjust).toRadians());switch(c.shape[0]){case "v2.1":var e=new Image;e.src=c.shape[1].src;c=Math.min(c.sizeScale[2]/e.width,c.sizeScale[2]/e.height);b&&(c*=2);e.width*=c;e.height*=c;b?d.clearRect(e.width/-2,e.height/-2,e.width,e.height):
d.drawImage(e,e.width/-2,e.height/-2,e.width,e.height);break;default:console.warn("unknown version ID")}d.setTransform(1,0,0,1,0,0)},renderWorld:function(){for(var a in variables.interactingObjects)variables.interactingObjects[a].draw()},clearCanvas:function(a){variables.leaveGame||(variables.context.clearRect(0,0,variables.canvas.width,variables.canvas.height),a||(this.renderWorld(),setTimeout(function(){functions.clearCanvas()},variables.eraseFullBoardFrequency)))},getMousePos:function(a){var b=
variables.canvas.getBoundingClientRect();return{x:(a.clientX-b.left).roundTo(variables.userAccuracy.mouse),y:(a.clientY-b.top).roundTo(variables.userAccuracy.mouse)}},isPressed:function(a,b){var d=variables.interactingObjects[variables.activeUser].user.keyboard;if("number"===typeof a)return d[a]?b?d[a][1]:d[a][0]:!1;if(Array.isArray(a)){for(d=0;d<a.length;d++)if(this.isPressed(a[d],b))return!0;return!1}console.warn("wrong input type")},gameMessage:function(a,b){var d=[];d.message="string"===typeof a?
a:a.message;d.target=a.target||"all";d.action=a.action||"post";d.origin=variables.activeUser||(variables.server?"server":authObject.authData.uid);d.localeTimestamp=firebase.database.ServerValue.TIMESTAMP;d=messageRef.push(functions.standardizeForFirebase(d));if(!b&&d.path.o){var c=messageRef.child(d.path.o[d.path.o.length-1]);setTimeout(function(){c.remove()},variables.messageTimeout)}},userMessage:function(a,b,d){b&&"string"===typeof b||console.warn("Wrong input '"+b+"'");a=$("<div class='userMessage "+
b+"'>"+a+"</div>");a.appendTo("body").fadeIn();a.delay(d||4E3).fadeOut("slow",function(){$(this).remove()})},reduceToRequired:function(a,b){var d={},c=b?b:a.minimalToRender;if(void 0===c)return a;for(var e in c)if("object"===typeof c[e])d[e]=functions.reduceToRequired(a[e],c[e]),jQuery.isEmptyObject(d[e])&&delete d[e];else if(!0===c[e])if(a[e])d[e]=a[e];else if("string"===typeof c[e])if("number"===typeof a[e])d[e]=a[e].roundTo(Object.byString(window,c[e]));else{switch(!0){case !1!==c[e]:case "function"===
typeof c[e]:console.warn("more investigation required")}return null}return d},standardizeForFirebase:function(a,b){return function c(a){var b,h;for(h in a)switch(b=a[h],!0){case void 0===b:case Infinity===b:case isReallyNaN(b):case "function"===typeof b:delete a[h];break;case "object"===typeof b:c(b)}return a}(b?clone(a):functions.reduceToRequired(a))},objectFactory:function(a,b,d){b||(b={});d||(d={});for(var c=0;c<(d.count||1);c++){var e=updateSome(new window[a],b);e.onCompleteConstruction();if(d.save||
d.count)variables.interactingObjects[e.uid]=e}return e}};Array.prototype.move=function(a,b){for(;0>a;)a+=this.length;for(;0>b;)b+=this.length;if(b>=this.length)for(var d=b-this.length;d--+1;)this.push(void 0);this.splice(b,0,this.splice(a,1)[0])};Array.prototype.toPolar=function(a){var b=Math.sqrt(Math.pow(this[0],2)+Math.pow(this[1],2)),d=Math.atan(this[1]/this[0]);return"object"===a?{radius:b,theta:d}:[b,d]};
Array.prototype.toCartesian=function(a){var b=this[0]*Math.cos(this[1]),d=this[0]*Math.sin(this[1]);return"object"===a?{x:b,y:d}:[b,d]};Number.prototype.toRadians=function(){return this*Math.PI/180};Number.prototype.toDegrees=function(){return 180*this/Math.PI};Number.prototype.min=function(a){return this<a?a:this};Number.prototype.max=function(a){return this>a?a:this};Number.prototype.minMax=function(a,b){return this.min(a).max(b)};
Number.prototype.roundTo=function(a){a||(a=1);return Math.round(this/a)*a};Number.prototype.cleanAngle=function(a){var b=this,d=360;a&&(d=2*Math.PI());b%=d;0>b&&(b+=d);return b%d};Number.prototype.steeringAngle=function(){var a=this.cleanAngle();return 180<a?a-360:a};CanvasRenderingContext2D.prototype.setFontSize=function(a){var b=this.font.split(" "),b=b[b.length-1];this.font=a+" "+b};
Object.byString=function(a,b){var d=a,c;c=b.replace(/\[(\w+)\]/g,".$1");c=c.replace(/^\./,"");c=c.split(".");for(var e=0,f=c.length;e<f;++e){var h=c[e];if(h in d)d=d[h];else return}return d};function rotatePoint(a,b,d,c,e){return{x:a*Math.cos(d)-b*Math.sin(d)+(c||0),y:a*Math.sin(d)+b*Math.cos(d)+(e||0)}}function getStandardAngle(a,b,d,c){return Math.atan2(b-(c||0),a-(d||0)).toDegrees().cleanAngle()}function getDistance(a,b,d,c){return Math.sqrt(Math.pow(a-d,2)+Math.pow(b-c,2))}
function rand(a,b){return Math.floor(Math.random()*(b-a))+a}function getFileExtension(a){-1!==a.indexOf("?")&&(a=a.substr(0,a.indexOf("?")));if(a)return a.substr((~-a.lastIndexOf(".")>>>0)+2);console.warn("No file name provided")}
var loadFile=function(a,b){var d=0,c=new Image;return function(a){var f,h=getFileExtension(a).toLowerCase();switch(h){case "":return;case "js":case "json":f=document.createElement("script");f.setAttribute("type","text/javascript");f.setAttribute("src",a);break;case "css":f=document.createElement("link");f.setAttribute("rel","stylesheet");f.setAttribute("type","text/css");f.setAttribute("href",a);break;case "jpg":case "jpeg":case "png":case "gif":c.src=a;break;default:console.warn("This file type is not supported: "+
h);return}$("head").append(f);b&&console.log("Loaded file: "+a);d++}}();function arrayifyArguments(a){for(var b=[],d=0;d<a.length;d++)b.push(a[d]);return b}function updateSome(){var a=arrayifyArguments(arguments);a.splice(0,0,!0);return jQuery.extend.apply({},a)}
var generatePushID=function(){var a=0,b=[];return function(){var d=(new Date).getTime(),c=d===a;a=d;for(var e=Array(8),f=7;0<=f;f--)e[f]="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(d%64),d=Math.floor(d/64);if(0!==d)throw Error("We should have converted the entire timestamp.");d=e.join("");if(c){for(f=11;0<=f&&63===b[f];f--)b[f]=0;b[f]++}else for(f=0;12>f;f++)b[f]=Math.floor(64*Math.random());for(f=0;12>f;f++)d+="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(b[f]);
if(20!=d.length)throw Error("Length should be 20.");return d}}();function doPolygonsIntersect(a,b){var d=[a,b],c,e,f,h,l,g,m,p;for(h=0;h<d.length;h++){var k=d[h];for(l=0;l<k.length;l++){c=k[l];e=k[(l+1)%k.length];var n=e.y-c.y,q=c.x-e.x;c=e=void 0;for(g=0;g<a.length;g++){f=n*a[g].x+q*a[g].y;if(!c||f<c)c=f;if(!e||f>e)e=f}m=p=void 0;for(g=0;g<b.length;g++){f=n*b[g].x+q*b[g].y;if(!m||f<m)m=f;if(!p||f>p)p=f}if(e<m||p<c)return!1}}return!0}
Array.prototype.toPolygonPathForm=function(a,b,d){var c=[];a||(a=[0,0]);b||(b=1);d||(d=0);for(var e=0;e<this.length;e++)c[e]=rotatePoint(this[e][0]*b,this[e][1]*b,d,a[0],a[1]);return c};
function clone(a){if(!a)return a;var b;[Number,String,Boolean].forEach(function(c){a instanceof c&&(b=c(a))});if("undefined"==typeof b)if("[object Array]"===Object.prototype.toString.call(a))b=[],a.forEach(function(a,d,f){b[d]=clone(a)});else if("object"==typeof a)if(a.nodeType&&"function"==typeof a.cloneNode)b=a.cloneNode(!0);else if(a.prototype)b=a;else if(a instanceof Date)b=new Date(a);else{b={};for(var d in a)b[d]=clone(a[d])}else b=a;return b}
function scrollTo(a,b){$("html, body").animate({scrollTop:$("#"+a).offset().top},b||2E3)}function isReallyNaN(a){return a!==a}var QueryURL=function(){for(var a={},b=window.location.search.substring(1).split("&"),d=0;d<b.length;d++){var c=b[d].split("=");if("undefined"===typeof a[c[0]])a[c[0]]=decodeURIComponent(c[1]);else if("string"===typeof a[c[0]]){var e=[a[c[0]],decodeURIComponent(c[1])];a[c[0]]=e}else a[c[0]].push(decodeURIComponent(c[1]))}return a}();
function weapon(){return updateSome(new displayObject,{"class":"weapon",gamePlay:{spread:0,launchCount:1,launches:Bullet,rateOfFire:30,cooldown:0,speedMultiplier:1,damageMultiplier:1,rangeMultiplier:1},appearance:{sizeScale:{2:.4*variables.sizeScale}},fire:function(a){this.gamePlay.cooldown=this.gamePlay.rateOfFire;var b,d=this.appearance,c=this.gamePlay,e=[];b=c.launchCount;c=c.spread;if(1===b)e=[c];else{e[b-1]=0;e[0]=c;for(var f=1;f<b-1;f++)e[f]=c/(b-1)*f}for(f=0;f<e.length;f++)b=new this.gamePlay.launches,
b.gamePlay.damage=b.gamePlay.damage*(a.damage||1)*this.gamePlay.damageMultiplier,b.gamePlay.speed=b.gamePlay.speed*(a.speed||1)*this.gamePlay.speedMultiplier,b.gamePlay.HP=b.gamePlay.HP*(a.range||1)*this.gamePlay.rangeMultiplier,b=updateSome(b,{appearance:{position:d.position,rotate:d.rotate},gamePlay:{immuneTo:a.immuneTo||[variables.activeUser]},physics:{velocity:[b.gamePlay.speed,-1*(d.rotate+(e[f]-c/2)).toRadians()].toCartesian()}}),variables.interactingObjects[b.uid]=b,b.save()}})}
function Lazer(){return updateSome(new weapon,{name:"Lazer",gamePlay:{launches:LazerBeam,rateOfFire:20,speed:50},appearance:{shape:["v2.1",{src:"/g/assets/images/weapons/kraad.png"}]}})}function Sniper(){return updateSome(new weapon,{name:"Sniper",gamePlay:{launches:Bullet,rateOfFire:20,speedMultiplier:1.5,damageMultiplier:3.5},appearance:{shape:["v2.1",{src:"/g/assets/images/weapons/pulse_rifle.png"}]}})}
function Shotgun(){return updateSome(new weapon,{name:"Shotgun",gamePlay:{launches:ShotgunBullet,rateOfFire:50,spread:18,launchCount:4,speedMultiplier:.9},appearance:{shape:["v2.1",{src:"/g/assets/images/weapons/shotgun.png"}]}})}function Pistol(){return updateSome(new weapon,{name:"Pistol",gamePlay:{launches:Bullet,rateOfFire:20},appearance:{shape:["v2.1",{src:"/g/assets/images/projectiles/missle-gray1.png"}]}})}
function Sword(){return updateSome(new weapon,{name:"Sword",gamePlay:{launches:Melee,launchCount:4,spread:65,rateOfFire:12},appearance:{shape:["v2.1",{src:"/g/assets/images/weapons/Arthas_sword.png"}]}})}function LittleSister(){return updateSome(new weapon,{name:"LittleSister",gamePlay:{launches:SisterShell,rateOfFire:7},appearance:{shape:["v2.1",{src:"/g/assets/images/weapons/Type-31_Rifle.png"}]}})}
function TestWeapon(){return updateSome(new weapon,{name:"TestWeapon",gamePlay:{launches:TestProjectile,rateOfFire:12,speed:10},appearance:{shape:["v2.1",{src:"/g/assets/images/weapons/purple_dominator.png"}]}})}function GrenadeLauncher(){return updateSome(new weapon,{name:"GrenadeLauncher",gamePlay:{launches:Explosive,rateOfFire:60},appearance:{shape:["v2.1",{src:"/g/assets/images/projectiles/missle-gray2.png"}]}})}
function SisterShell(){return updateSome(new orb,{name:"SisterShell",gamePlay:{damage:45,HP:25,speed:18},appearance:{shape:["v2.1",{src:"/g/assets/images/projectiles/orbs/Dream_Smoke_Ball_Sprite.png"}]}})}
function OnContactEffect(){return updateSome(new projectile,{name:"OnContactEffect",gamePlay:{damage:0,HP:4},appearance:{shape:["v2.1",{src:"/g/assets/images/projectiles/on-contact-effect.png"}],sizeScale:{2:.4*variables.sizeScale}},minimalToRender:{appearance:!1,gamePlay:!1,physics:!1,user:!1},physics:{mass:10}})}
function ShotgunBullet(){return updateSome(new Bullet,{name:"ShotgunBullet",gamePlay:{damage:12,HP:150},appearance:{shape:["v2.1",{src:"/g/assets/images/projectiles/blue-lazer.png"}]},leaveArena:function(){return!0}})}
function TestProjectile(){return updateSome(new projectile,{name:"TestProjectile",gamePlay:{damage:100,damageType:"melee",HP:250,speed:10},appearance:{shape:["v2.1",{src:"/g/assets/images/projectiles/missle-darkgray2.png"}],sizeScale:{2:.85*variables.sizeScale}},physics:{mass:60}})}
function LazerBeam(){return updateSome(new projectile,{name:"LazerBeam",gamePlay:{damage:120,damageType:"energy",speed:50},appearance:{shape:["v2.1",{src:"/g/assets/images/projectiles/solid-red-lazer.jpg"}],sizeScale:{2:.9*variables.sizeScale}},physics:{mass:20},deathEffect:function(){var a=this.gamePlay,b=variables,d=this.appearance;if(a.hasDied[1]&&10<b.timeStamp-a.hasDied[1])return!0;a.HP=22;d.shape[1].src="/g/assets/images/projectiles/blue-lazer.png";d.sizeScale[2]/=4;a.speed*=3;a.damageMultiplier*=
3;this.leaveArena=function(a){var b=this.physics.velocity,d=Math.abs(b[0]),h=Math.abs(b[1]);switch(a){case "left":b[0]=d;break;case "right":b[0]=0-d;break;case "top":b[1]=0-h;break;case "bottom":b[1]=h}return!1};return!1}})}
function Bullet(){return updateSome(new projectile,{name:"Bullet",gamePlay:{damage:20,HP:150,speed:20},appearance:{shape:["v2.1",{src:"/g/assets/images/projectiles/8bit-green.png"}]},physics:{mass:10},leaveArena:function(a){var b=this.physics.velocity;switch(a){case "top":b[1]=0-Math.abs(b[1]);break;case "bottom":b[1]=Math.abs(b[1]);break;case "left":case "right":return!0}}})}
function orb(){return updateSome(new projectile,{appearance:{spinDirection:rand(0,2)?1:-1,spinSpeed:rand(3,7),sizeScale:{2:.15*variables.sizeScale}},gamePlay:{speed:2,damageType:"ranged"},physics:{mass:5},cycleEffect:function(){var a=this.appearance;a.rotate+=a.spinDirection*a.spinSpeed}})}
function Explosive(){return updateSome(new orb,{name:"Explosive",gamePlay:{damage:50,damageType:"explosive",HP:400,speed:7.2},appearance:{sizeScale:{2:.7*variables.sizeScale},shape:["v2.1",{src:"/g/assets/images/projectiles/orbs/circular-lazer-shot.png"}]},physics:{mass:30},leaveArena:function(a){var b=this.physics.velocity,d=this.appearance;switch(a){case "top":case "bottom":return!0;case "left":d.position[0]=variables.canvas.width-this.physics.hitBox.simple[1]*d.sizeScale[2]-1;break;case "right":b[0]*=
-2}},deathEffect:function(){var a=this.gamePlay,b=variables;if(a.hasDied[1]&&10<b.timeStamp-a.hasDied[1])return!0;this.gamePlay.HP=11;this.physics.velocity[0]/=2;this.physics.velocity[1]/=2;this.appearance.sizeScale[2]*=1.1;this.minimalToRender.appearance.sizeScale[2]=!0;return!1}})}
function Melee(){return updateSome(new projectile,{name:"Melee",gamePlay:{damage:65,ranged:!1,damageType:"melee",HP:10,speed:40},appearance:{shape:["v2.1",{src:"/g/assets/images/projectiles/blue-sword-arc.png"}],sizeScale:{2:1.2*variables.sizeScale}},physics:{mass:60}})}
function displayObject(){return{uid:generatePushID(),name:"displayObject","class":"generic",gamePlay:{HP:1001,owner:variables.activeUser,immuneTo:["no-one"]},appearance:{shape:["v2.1",{src:"/g/assets/images/icons/missing.gif"}],rotate:0,sizeScale:{0:1,1:3*variables.sizeScale,2:1},position:variables.canvas?[rand(0,variables.canvas.width),rand(0,variables.canvas.height)]:[0,0]},physics:{mass:0,velocity:[0,0],hitBox:{simple:[-.5,.5,.5,-.5],corners:[[.5,.5],[.5,-.5],[-.5,-.5],[-.5,.5]],testPoints:[[1,
1],[1,-1],[-1,1],[-1,-1]]}},minimalToRender:{uid:!0,name:!0,gamePlay:{owner:!0,immuneTo:!0},appearance:{sizeScale:{2:!0},rotate:!0,position:!0}},leaveArena:function(a,b){console.log(this.name,"left the arena to the",a,"--\x3e Props:",b);return!0},gameCycle:function(){console.log(this.name,"fired a gameCycle")},draw:function(){functions.renderObject(this.appearance)},erase:function(){functions.renderObject(this.appearance,!0)},save:function(){this.isOwner()&&(variables.leaveGame||variables.singlePlayerMode||
objectsRef.update(function(a){var b={};b[a.uid]=functions.standardizeForFirebase(a);return b}(this)))},collideWith:function(a){console.log(this.name,"collided with",a.name)},onCompleteConstruction:function(){},isOwner:function(){return this.gamePlay.owner===variables.activeUser?!0:!1}}}
function projectile(){return updateSome(new displayObject,{"class":"projectile",appearance:{sizeScale:{2:.2*variables.sizeScale}},gamePlay:{damage:40,speed:20,ranged:!0,damageType:"generic",hasDied:[0,!1],HP:100},minimalToRender:{gamePlay:{damage:!0,HP:!0,speed:!0},physics:{velocity:!0}},die:function(){var a=this.gamePlay,b=variables;a.hasDied[0]++;a.hasDied[1]||(a.hasDied[1]=b.timeStamp);if(!this.deathEffect())return this.minimalToRender.gamePlay.hasDied=!0,this.save(),!1;this.erase();this.isOwner()&&
!a.diedAwhileAgo?a.diedAwhileAgo=b.timeStamp:(delete b.interactingObjects[this.uid],objectsRef.child(this.uid).remove())},leaveArena:function(){return!0},gameCycle:function(){var a=this.physics,b=this.appearance.position;this.gamePlay.HP--;this.cycleEffect();b[0]+=a.velocity[0];b[1]-=a.velocity[1];this.isOwner()&&0===variables.timeStamp%variables.projectileSaveFrequency&&this.save()},collideWith:function(a){switch(a["class"]){case "userObject":case "robot":a=this.appearance.position,"OnContactEffect"!==
this.name&&functions.objectFactory("OnContactEffect",{appearance:{position:a}},{save:!0})}this.die()},cycleEffect:function(){var a=this.physics;this.appearance.rotate=getStandardAngle(a.velocity[0],-1*a.velocity[1])},deathEffect:function(){return!0}})}
function userObject(){return updateSome(new displayObject,{"class":"userObject",appearance:{sizeScale:{0:.8*variables.sizeScale,1:1.3*variables.sizeScale,2:1*variables.sizeScale}},gamePlay:{buttonMapping:{cw:82,cw_last_pressed:-1,dn:[40,83],fi:32,lt:[37,65],rt:[39,68],sb:81,ss:69,up:[38,87],sl:90,sr:67},HP:1500,maxHP:2E3,resizeSpeed:15,rotateSpeed:5,shieldRegen:5,shieldBurnOut:125,currentShieldBurnOut:0,maxShields:300,sideThrusting:{rate:1,max:16,extraSpeed:3,extraAcceleration:30,current:0,displacement:0,
burned:!1,controlling:!1},speed:15,damageMultiplier:1,projectileSpeed:1,weaponKeywords:["Sniper","Sword","GrenadeLauncher","TestWeapon","Lazer"]},physics:{mass:300,userVelocity:[0,0]},user:{keyboard:{},level:0,mouse:{x:0,y:0,down:!1},name:"Johnny Appleseed",stats:{dateCreated:firebase.database.ServerValue.TIMESTAMP,lastLogin:firebase.database.ServerValue.TIMESTAMP,stats:"other stats",totalTimePlayed:0},upgrades:{damageBoost:1},username:"J. Appleseed",xp:0,xpNeeded:4E3,publicProfileImg:"/g/assets/images/defaultProfilePic.png",
availableToPublic:!0,summary:function(){return"This is a very fast ship with moderate sheilds, but damage to destroy all enemies forever!"}},minimalToRender:{gamePlay:{shields:!0,weaponKeywords:!0,HP:!0},physics:{velocity:!0},user:{publicProfileImg:!0,username:!0}},leaveArena:function(a,b){var d=this.physics,c=this.appearance.position,e=variables.canvas;switch(a){case "left":case "right":d.velocity[0]=0;c[0]="left"===a?b[a]:e.width-b[a];break;case "top":case "bottom":d.velocity[1]=0,c[1]="top"===
a?b[a]:e.height-b[a]}this.physics=d;this.appearance.position=c},gameCycle:function(){this.applyGameLogic();this.isOwner()&&0===variables.timeStamp%variables.userSaveFrequency&&this.save()},applyGameLogic:function(){var a=variables,b=this.appearance,d=b.position,c=this.gamePlay,e=c.weapons,f=this.physics,h=this.isPressed("up"),l=this.isPressed("dn"),g=this.isPressed("lt"),m=this.isPressed("rt"),p=this.isPressed("sr"),k=this.isPressed("sl"),n=0,q;this.isOwner()&&(1===p+k||c.sideThrusting.controlling?
(e=c.sideThrusting,1!==p+k||e.burned?(e.current-=1/e.rate,q=1/e.rate,0<e.displacement&&(q*=-1),e.displacement+=q):(++e.current,f.userVelocity=[e.extraSpeed*c.speed*(p-k),(b.rotate+90).toRadians()].toCartesian(),e.displacement+=p-k),e.current>=e.max?e.burned=!0:0===e.current?(e.burned&&(e.burned=!1),f.velocity=[0,0],f.userVelocity=[0,0]):n=e.current/e.max/2*a.accelerationConst*((e.max-e.current)/e.max)/(f.mass/e.extraAcceleration),e.controlling=0!==e.current?!0:!1):(1===g+m&&(b.rotate=g?b.rotate-c.rotateSpeed:
b.rotate+c.rotateSpeed),0===(b.rotate=b.rotate.cleanAngle())%90&&++b.rotate,f.userVelocity=[c.speed*(h-l)*(.5*l||1),b.rotate.toRadians()].toCartesian(),n=this.isPressed("ss"),p=this.isPressed("sb"),1===n+p&&(b=b.sizeScale,k=(b[1]-b[0])/c.resizeSpeed,n&&(k*=-1),n&&b[0]>=b[2]||p&&b[1]<=b[2]||(n=c.HP/c.maxHP,b[2]+=k,c.maxHP-=25*k,c.maxShields-=25*k,c.shieldRegen-=.04*k*1.1,c.speed-=.16*k,c.damageMultiplier+=.04*k,c.HP=n*c.maxHP)),e[0].gamePlay.cooldown--,this.isPressed("fi")&&0>=e[0].gamePlay.cooldown&&
this.fireWeapon(),this.isPressed("cw")&&c.cw_last_pressed!==(q=this.isPressed("cw",!0))&&(c.cw_last_pressed=q,this.changeWeapon()),n=a.accelerationConst/f.mass),f.velocity[0]+=n*(f.userVelocity[0]-f.velocity[0]),f.velocity[1]+=n*(f.userVelocity[1]-f.velocity[1]));this.isOwner()&&0>=c.currentShieldBurnOut--&&(c.shields+=c.shieldRegen);c.shields=Math.min(c.shields,c.maxShields);c.HP=Math.min(c.HP,c.maxHP);d[0]+=f.velocity[0];d[1]+=f.velocity[1]},isPressed:function(a,b){return functions.isPressed(this.gamePlay.buttonMapping[a],
b)},draw:function(){functions.renderObject(this.appearance);functions.renderObject(updateSome(this.gamePlay.weapons[0],{appearance:{position:this.appearance.position,rotate:this.appearance.rotate}}).appearance);var a=variables.display,b=a.HPbar,d=variables.context,c=this.appearance.position,e=b.height,f=b.width,h=[],l,g=this.gamePlay;l=g.sideThrusting;d.setFontSize(e+"px");h.push({present:b.HPcolor.present,absent:b.HPcolor.absent,percent:g.HP/g.maxHP,text:Math.round(g.HP)+" / "+Math.round(g.maxHP)});
var m;m=0<g.currentShieldBurnOut&&this.isOwner()?"Burned out for: "+Math.ceil(g.currentShieldBurnOut/10):m=Math.round(g.shields)+" / "+Math.round(g.maxShields);h.push({present:b.shieldColor.present,absent:b.shieldColor.absent,percent:g.shields/g.maxShields,text:m});this.isOwner()&&"userObject"===this["class"]&&(g=g.weapons[0],m=g.gamePlay,h.push({present:b.weaponColor.present,absent:b.weaponColor.absent,percent:(m.rateOfFire-m.cooldown.min(0))/m.rateOfFire,text:g.name}));0<l.current&&h.push({present:b.strifeColor.present,
absent:b.strifeColor.absent,percent:l.current/l.max,text:"Moving Sideways!",backwards:0>l.displacement});d.textAlign="start";for(g=0;g<h.length;g++)l=h[g],d.fillStyle=l.absent||"white",d.fillRect(c[0]-f/2,c[1]-b.y_offset-e*g,f,e),d.fillStyle=l.present||"black",l.backwards?(m=f*l.percent,d.fillRect(c[0]-f/2+(f-m),c[1]-b.y_offset-e*g,m,e)):d.fillRect(c[0]-f/2,c[1]-b.y_offset-e*g,f*l.percent,e),l.text&&(d.fillStyle=a.usernameColor,d.fillText(l.text,c[0]-f/2+b.left_pad,c[1]-b.y_offset-e*(g-1)-b.bottom_pad));
d.textAlign="center";d.fillText(this.user.username,c[0],c[1]-b.y_offset-e*h.length);e=new Image;a=a.profilePic;e.src=this.user.publicProfileImg;d.drawImage(e,c[0]+a.x_offset,c[1]-a.y_from_HPbar-b.y_offset,a.size,a.size)},erase:function(){functions.renderObject(this.appearance,!0);functions.renderObject(this.gamePlay.weapons[0].appearance,!0);var a=this.appearance.position,b=variables.display,d=b.HPbar,b=-1*Math.max(d.width/2,-1*b.profilePic.x_offset),c=5;this.isOwner()&&"userObject"===this["class"]&&
c++;c*=d.height;variables.context.clearRect(b+a[0]-1,a[1]-d.y_offset-(c-d.height)+1,-1*b+d.width/2+2,c+2)},fireWeapon:function(){var a={damage:this.gamePlay.damageMultiplier,speed:this.gamePlay.projectileSpeed};"robot"===this["class"]&&(a.immuneTo=[this.uid,"robot"]);this.gamePlay.weapons[0].fire(a)},changeWeapon:function(){var a=this.gamePlay,b=a.weapons,a=a.weaponKeywords;b.move(0,-1);a.move(0,-1);b[0].gamePlay.cooldown=b[0].gamePlay.rateOfFire;variables.activeUserGameServer.child("gamePlay/weaponKeywords/0").set(b[0].name)},
takeDamage:function(a){var b=this.gamePlay,d=b.HP,c=b.shields;this.isOwner()&&(a<=c&&0>=b.currentShieldBurnOut?c-=a:(c=0,0>=b.currentShieldBurnOut&&(b.currentShieldBurnOut=b.shieldBurnOut),d-=a-c),this.gamePlay.HP=d,this.gamePlay.shields=c)},collideWith:function(a){var b=[this.gamePlay.speed/this.physics.mass],d=this.appearance.position,c=a.appearance.position,e=a.gamePlay;switch(a["class"]){case "projectile":this.takeDamage(a.gamePlay.damage);break;case "userObject":case "robot":b[1]=getStandardAngle(d[0],
d[1],c[0],c[1]).toRadians();b=b.toCartesian();this.physics.velocity[0]+=b[0];this.physics.velocity[1]+=b[1];this.takeDamage(e.HP*e.damageMultiplier/variables.reduceRammingDmg);break;default:console.warn(a["class"],"unknown class of other object")}},die:function(){this.erase();this.isOwner()&&(functions.userMessage("You just died!","error"),this.respawn())},respawn:function(){var a=this.gamePlay,b=this.appearance.position;a.HP=a.maxHP;a.shields=a.maxShields;a.currentShieldBurnOut=0;this.appearance.rotate=
rand(0,360);b[0]=rand(0,variables.canvasSize[0]);b[1]=rand(0,variables.canvasSize[1])},onCompleteConstruction:function(){var a=this.gamePlay,b=a.weaponKeywords;a.weapons=[];for(var d in b)!1===isNaN(parseInt(d,10))&&(a.weapons[d]=functions.objectFactory(b[d]));a.HP=a.maxHP;a.shields=a.maxShields}})}
var fromPHP={},database=mainFirebase.child("users"),gameServer=mainFirebase.child("gameServer/chrome"),whitelistRef=gameServer.child("whiteList"),objectsRef=gameServer.child("interactingObjects/active"),pingsRef=gameServer.child("lastPings"),messageRef=gameServer.child("messages"),authObject={serverPassword:"big5",canvas:"canvas",ownerLogin:function(){var a=!1;if(this.isOwnerLoggedIn())a=!0;else{var b=prompt("What is the owner password?");b===this.serverPassword&&(Cookies.set("ServerPassword",b,{expires:7}),
a=!0)}return a?(this.onOwnerAuthStateChanged(),!0):!1},isOwnerLoggedIn:function(){return Cookies.get("ServerPassword")===this.serverPassword?!0:!1},ownerLogout:function(){Cookies.remove("ServerPassword");functions.userMessage("Thanks for preserving the integrity of our special content","success",2E3);this.onOwnerAuthStateChanged();return!1},onOwnerAuthStateChanged:function(){authObject.isOwnerLoggedIn()?(functions.userMessage("You are an owner","success",2E3),$("#ownerButton").html("Logout as owner").attr("onclick",
"authObject.ownerLogout()")):$("#ownerButton").html("Login as owner").attr("onclick","authObject.ownerLogin()")},login:function(a){a.app&&(a=new firebase.auth.GoogleAuthProvider,firebase.auth().signInWithPopup(a))},logout:function(){firebase.auth().signOut()}};$(document).ready(authObject.onOwnerAuthStateChanged);
firebase.auth().onAuthStateChanged(function(a){var b=$("#login"),d=$("#logout");a?(a.displayName||(a.displayName=a.email.substr(0,a.email.indexOf("@"))),authObject.authData=a,console.log("Authenticated successfully with payload:",a),b.html("Logged in as "+a.displayName).prop("disabled","true"),d.removeAttr("disabled")):(console.log("Signed out :("),b.html("Login with Google").removeAttr("disabled"),d.prop("disabled","true"),authObject.authData=!1)});
variables={interactingObjects:{},timeStamp:0,canvasID:"canvas",activeUser:"generic",leaveGame:!1,singlePlayerMode:!1,debugFlags:{showFilesLoaded:!0},display:{HPbar:{HPcolor:{},shieldColor:{},weaponColor:{}},usernameColor:"#fff"}};
function initiateWorld(){variables.canvas=document.getElementById(variables.canvasID);variables.context=variables.canvas.getContext("2d");authObject.authData&&(variables.activeUser=authObject.authData.uid);var a=function(a){switch(a){case "canvasSize":variables.canvas.width=variables.canvasSize[0],variables.canvas.height=variables.canvasSize[1]}};gameServer.child("gameVariables").on("child_added",function(b){variables[b.key]=b.val();a(b.key)});gameServer.child("gameVariables").on("child_changed",
function(b){variables[b.key]=b.val();a(b.key)});init()}
function listenToObjectsRef(){objectsRef.on("child_added",function(a){var b=functions.objectFactory(a.val().name,a.val(),{save:!0});if(a.key!==variables.activeUser)a.ref.on("child_added",function(a){var c=b[a.key];updateSome(c,a.val());a.ref.on("child_changed",function(a){var d=c[a.key]=a.val();"weaponKeywords"===a.key&&(b.gamePlay.weapons[0]=functions.objectFactory(d[0]))})})});objectsRef.on("child_removed",function(a){delete variables.interactingObjects[a.key];a.ref.off()})};
function init(){var a=variables;database.child(a.activeUser).once("value").then(function(b){b=b.val();functions.objectFactory(b.name,b,{save:!0});a.activeUserGameServer=objectsRef.child(a.activeUser);a.activeUserDatabase=database.child(a.activeUser);a.activeUserDatabase.child("user/stats/lastLogin").set(firebase.database.ServerValue.TIMESTAMP);modeInit()})}
function gameLoop(){if(!variables.leaveGame){var a=variables;a.singlePlayerMode&&(AI.user.stateLog.innerHTML="");for(var b in a.interactingObjects){var c=variables.interactingObjects[b],e=c.appearance,f=c.physics,k=e.position,d;c.erase();d=c.gameCycle();!d&&0>=c.gamePlay.HP&&(d=!0);if(c.isOwner()&&("userObject"===c["class"]||"robot"===c["class"])){var l=f.hitBox.corners.toPolygonPathForm(e.position,e.sizeScale[2]),m,g,n,h=c.uid,p;for(p in a.interactingObjects)h!==p&&(g=a.interactingObjects[p],-1===
g.gamePlay.immuneTo.indexOf(h)&&-1===g.gamePlay.immuneTo.indexOf(c["class"])&&(n=g.appearance,m=n.position,m=g.physics.hitBox.corners.toPolygonPathForm(m,n.sizeScale[2],n.rotate.toRadians()),doPolygonsIntersect(l,m)&&(c.collideWith(g),g.collideWith(c))))}l=e.sizeScale[2]*f.hitBox.simple[0]*-1;g=e.sizeScale[2]*f.hitBox.simple[1]*1;h=e.sizeScale[2]*f.hitBox.simple[2]*1;e=e.sizeScale[2]*f.hitBox.simple[3]*-1;f={top:l,bottom:h,left:e,right:g};!d&&k[0]<e&&(d=c.leaveArena("left",f));!d&&k[0]>a.canvas.width-
g&&(d=c.leaveArena("right",f));!d&&k[1]<l&&(d=c.leaveArena("top",f));!d&&k[1]>a.canvas.height-h&&(d=c.leaveArena("bottom",f));d&&c.die()}functions.renderWorld();a.timeStamp++;setTimeout(gameLoop,a.gameSpeed)}}
function clientActivate(){var a=variables;a.debugFlags.showStagesPerformed&&console.log(a.activeUser+": We just got accepted to the game");a.userBackup&&(a.interactingObjects[a.activeUser]=a.userBackup);document.getElementById("control_buttons").style.display="none";$("body").keydown(function(b){a.interactingObjects[a.activeUser].user.keyboard[b.keyCode]||(a.interactingObjects[a.activeUser].user.keyboard[b.keyCode]=[!0,a.timeStamp],a.debugFlags.showKeyboardActions&&console.log(b.keyCode+" is pressed"))});
$("body").keyup(function(b){delete a.interactingObjects[a.activeUser].user.keyboard[b.keyCode];a.debugFlags.showKeyboardActions&&console.log(b.keyCode+" is released")});a.leaveGame=!0;setTimeout(function(){a.leaveGame=!1;var b=a.interactingObjects[a.activeUser];a.activeUserGameServer.set(functions.standardizeForFirebase(b,!0));b.respawn();gameLoop();ping();functions.clearCanvas()},3*a.gameSpeed)}
function clientDeactivate(){var a=variables;a.debugFlags.showStagesPerformed&&console.log(a.activeUser+": We were just rejected/ejected from the game");document.getElementById("control_buttons").style.display="";a.leaveGame=!0;$("body").off();a.userBackup=a.interactingObjects[a.activeUser];a.activeUserGameServer.set(null);functions.userMessage("We were kicked from the game","error")}
function ping(){variables.leaveGame||(pingsRef.child(variables.activeUser).set(firebase.database.ServerValue.TIMESTAMP),setTimeout(ping,variables.pingFrequency))}function listenToMessages(){var a=variables;messageRef.on("child_added",function(b){b.val().target===a.activeUser&&b.ref.remove()})}
function waitForWhitelist(){var a=variables;whitelistRef.on("child_added",function(b){b.key===a.activeUser&&(!0===b.val()?clientActivate():!1===b.val()?clientDeactivate():console.warn("Weird value in the firebase"))});whitelistRef.on("child_changed",function(b){b.key===a.activeUser&&(!0===b.val()?clientActivate():!1===b.val()?clientDeactivate():console.warn("Weird data value in the firebase"))});whitelistRef.on("child_removed",function(b){b.key===a.activeUser&&clientDeactivate()})}
function goToMenu(){Cookies.get("mode")&&(Cookies.remove("mode"),location.reload())}firebase.auth().onAuthStateChanged(function(a){a?initiateWorld():goToMenu()});
<?php if($mode === 'singleplayer') searchfilereturnline('min/sprite.js',$sprite);
      else listallsprites(); ?>
</script>
<?php
if($mode === 'multiplayer')         require(realpath('min/multi.html'));
elseif($mode === 'singleplayer')    require(realpath('min/single.html'));
else                                require(realpath('min/choose.html'));
?>
<style>
body{margin:0;padding:0;overflow:hidden;background:url('/g/assets/images/background.jpg');background-position-x:center;position:relative;height:100vh}canvas{border:6px solid #0e1f5b;background:rgba(225,225,225,0.4)}.centerAll{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%)}.userMessage{font-family:Arial,Helvetica,sans-serif;font-size:13px;border:1px solid;padding:15px 10px 15px 50px;background-repeat:no-repeat;background-position:10px center;position:fixed;bottom:5px;right:5px;z-index:1;display:none}
.info{color:#00529B;background-color:#BDE5F8;background-image:url('/g/assets/images/icons/blue-i.png')}.success{color:#4F8A10;background-color:#DFF2BF;background-image:url('/g/assets/images/icons/green-check.png')}.warning{color:#9F6000;background-color:#FEEFB3;background-image:url('/g/assets/images/icons/yellow-exclamation.png')}.error{color:#D8000C;background-color:#FFBABA;background-image:url('/g/assets/images/icons/red-x.png')}.validation{color:#D63301;background-color:#FFCCBA;
background-image:url('/g/assets/images/icons/blue-exclamation.png')}#client div.fb-like{position:absolute;bottom:2px;left:2px;width:96px;overflow:hidden}#client[mode='chooserole'] canvas, #client[mode='chooserole'] #back2chooseRole{display:none}#back2chooseRole{cursor:pointer;width:187px;padding:3px;left:14px}#back2chooseRole small{color:#3a1637;letter-spacing:-0.2px}#stateLog{display:none;background:#859bc3;background:rgba(28,83,183,0.77);position:fixed;padding:5px;color:#dde7f7;font-size:12px;right:0}
#winner{display:none;background:green;font-size:10vw;font-family:'Righteous',cursive;padding:2vw}.myButton{box-shadow:3px 4px 0px 0px #8a2a21;border-radius:18px;background:linear-gradient(to bottom, #c62d1f 5%, #f24437 100%);border:1px solid #d02718;display:inline-block;cursor:pointer;color:#fff;font-family:Arial;font-size:17px;padding:0.45em 2.6em;text-decoration:none;text-shadow:0px 1px 0px #810e05;margin-bottom:8px}.myButton:hover,.myButton:focus{background:linear-gradient(to bottom, #f24437 5%, #c62d1f 100%)}
.myButton:focus{border:1px solid red}.myButton:disabled{background:gray}.arrow_box{position:relative;background:#ec0035;border-radius:3px;border-bottom-right-radius:5px;border-top-right-radius:5px}.arrow_box:after{right:100%;top:50%;border:solid transparent;content:" ";height:0;width:0;position:absolute;pointer-events:none;border-color:rgba(255, 240, 0, 0);border-right-color:#ec0035;border-width:12px;margin-top:-12px}
</style>