<script>
var functions={renderObject:function(b,c){var e=variables.context,d=b.appearance?b.appearance:b;d.translate=d.translate||[0,0];d.rotateAdjust=d.rotateAdjust||0;e.translate(d.position[0]+d.translate[0],d.position[1]+d.translate[1]);e.rotate((d.rotate+d.rotateAdjust).toRadians());switch(d.shape[0]){case "v2.1":var f=new Image;f.src=d.shape[1].src;d=Math.min(d.sizeScale[2]/f.width,d.sizeScale[2]/f.height);f.width*=d;f.height*=d;c?e.clearRect(f.width/
-2,f.height/-2,f.width,f.height):e.drawImage(f,f.width/-2,f.height/-2,f.width,f.height);break;default:console.warn("unknown version ID")}e.setTransform(1,0,0,1,0,0)},renderWorld:function(){for(var b in variables.interactingObjects)variables.interactingObjects[b].draw()},clearCanvas:function(b){variables.leaveGame||(variables.context.clearRect(0,0,variables.canvas.width,variables.canvas.height),b||(this.renderWorld(),setTimeout(function(){functions.clearCanvas()},variables.eraseFullBoardFrequency)))},
getMousePos:function(b){var c=variables.canvas.getBoundingClientRect();return{x:(b.clientX-c.left).roundTo(variables.userAccuracy.mouse),y:(b.clientY-c.top).roundTo(variables.userAccuracy.mouse)}},isPressed:function(b,c){var e=variables.interactingObjects[variables.activeUser].user.keyboard;if("number"===typeof b)return e[b]?c?e[b][1]:e[b][0]:!1;if(Array.isArray(b)){for(e=0;e<b.length;e++)if(this.isPressed(b[e],c))return!0;return!1}console.warn("wrong input type")},gameMessage:function(b,c){var e=
[];e.message="string"===typeof b?b:b.message;e.target=b.target||"all";e.action=b.action||"post";e.origin=variables.activeUser||(variables.server?"server":authObject.authData.uid);e.localeTimestamp=firebase.database.ServerValue.TIMESTAMP;e=messageRef.push(functions.standardizeForFirebase(e));if(!c&&e.path.o){var d=messageRef.child(e.path.o[e.path.o.length-1]);setTimeout(function(){d.remove()},variables.messageTimeout)}},userMessage:function(b,c,e){c&&"string"===typeof c||console.warn("Wrong input '"+
c+"'");b=$("<div class='userMessage "+c+"'>"+b+"</div>");b.appendTo("body").fadeIn();b.delay(e||4E3).fadeOut("slow",function(){$(this).remove()})},reduceToRequired:function(b,c){var e={},d=c?c:b.minimalToRender;if(void 0===d)return b;for(var f in d)if("object"===typeof d[f])e[f]=functions.reduceToRequired(b[f],d[f]),jQuery.isEmptyObject(e[f])&&delete e[f];else if(!0===d[f])if(b[f])e[f]=b[f];else if("string"===typeof d[f])if("number"===typeof b[f])e[f]=b[f].roundTo(Object.byString(window,d[f]));else{switch(!0){case !1!==
d[f]:case "function"===typeof d[f]:console.warn("more investigation required")}return null}return e},standardizeForFirebase:function(b,c){return function d(b){var c,k;for(k in b)switch(c=b[k],!0){case void 0===c:case Infinity===c:case isReallyNaN(c):case "function"===typeof c:delete b[k];break;case "object"===typeof c:d(c)}return b}(c?clone(b):functions.reduceToRequired(b))},objectFactory:function(b,c,e){c||(c={});e||(e={});for(var d=0;d<(e.count||1);d++){var f=updateSome(new window[b],c);f.onCompleteConstruction();
if(e.save||e.count)variables.interactingObjects[f.uid]=f}return f}};
(function(b){if("function"===typeof define&&define.amd)define(b);else if("object"===typeof exports)module.exports=b();else{var c=window.Cookies,e=window.Cookies=b();e.noConflict=function(){window.Cookies=c;return e}}})(function(){function b(){for(var b=0,c={};b<arguments.length;b++){var f=arguments[b],g;for(g in f)c[g]=f[g]}return c}function c(e){function d(c,g,k){var m;if("undefined"!==typeof document){if(1<arguments.length){k=b({path:"/"},d.defaults,k);if("number"===typeof k.expires){var h=new Date;
h.setMilliseconds(h.getMilliseconds()+864E5*k.expires);k.expires=h}try{m=JSON.stringify(g),/^[\{\[]/.test(m)&&(g=m)}catch(r){}g=e.write?e.write(g,c):encodeURIComponent(String(g)).replace(/%(23|24|26|2B|3A|3C|3E|3D|2F|3F|40|5B|5D|5E|60|7B|7D|7C)/g,decodeURIComponent);c=encodeURIComponent(String(c));c=c.replace(/%(23|24|26|2B|5E|60|7C)/g,decodeURIComponent);c=c.replace(/[\(\)]/g,escape);return document.cookie=[c,"=",g,k.expires&&"; expires="+k.expires.toUTCString(),k.path&&"; path="+k.path,k.domain&&
"; domain="+k.domain,k.secure?"; secure":""].join("")}c||(m={});for(var h=document.cookie?document.cookie.split("; "):[],n=/(%[0-9A-Z]{2})+/g,q=0;q<h.length;q++){var l=h[q].split("="),p=l[0].replace(n,decodeURIComponent),l=l.slice(1).join("=");'"'===l.charAt(0)&&(l=l.slice(1,-1));try{l=e.read?e.read(l,p):e(l,p)||l.replace(n,decodeURIComponent);if(this.json)try{l=JSON.parse(l)}catch(r){}if(c===p){m=l;break}c||(m[p]=l)}catch(r){}}return m}}d.set=d;d.get=function(b){return d(b)};d.getJSON=function(){return d.apply({json:!0},
[].slice.call(arguments))};d.defaults={};d.remove=function(c,e){d(c,"",b(e,{expires:-1}))};d.withConverter=c;return d}return c(function(){})});Array.prototype.move=function(b,c){for(;0>b;)b+=this.length;for(;0>c;)c+=this.length;if(c>=this.length)for(var e=c-this.length;e--+1;)this.push(void 0);this.splice(c,0,this.splice(b,1)[0])};
Array.prototype.toPolar=function(b){var c=Math.sqrt(Math.pow(this[0],2)+Math.pow(this[1],2)),e=Math.atan(this[1]/this[0]);return"object"===b?{radius:c,theta:e}:[c,e]};Array.prototype.toCartesian=function(b){var c=this[0]*Math.cos(this[1]),e=this[0]*Math.sin(this[1]);return"object"===b?{x:c,y:e}:[c,e]};Number.prototype.toRadians=function(){return this*Math.PI/180};Number.prototype.toDegrees=function(){return 180*this/Math.PI};Number.prototype.min=function(b){return this<b?b:this};
Number.prototype.max=function(b){return this>b?b:this};Number.prototype.minMax=function(b,c){return this.min(b).max(c)};Number.prototype.roundTo=function(b){b||(b=1);return Math.round(this/b)*b};Number.prototype.cleanAngle=function(b){var c=this,e=360;b&&(e=2*Math.PI());c%=e;0>c&&(c+=e);return c%e};Number.prototype.steeringAngle=function(){var b=this.cleanAngle();return 180<b?b-360:b};
String.prototype.upperFirst=function(){console.log("called a function that is on the chopping block");return this.charAt(0).toUpperCase()+this.slice(1)};CanvasRenderingContext2D.prototype.setFontSize=function(b){var c=this.font.split(" "),c=c[c.length-1];this.font=b+" "+c};Object.byString=function(b,c){var e=b,d;d=c.replace(/\[(\w+)\]/g,".$1");d=d.replace(/^\./,"");d=d.split(".");for(var f=0,g=d.length;f<g;++f){var k=d[f];if(k in e)e=e[k];else return}return e};
function rotatePoint(b,c,e,d,f){return{x:b*Math.cos(e)-c*Math.sin(e)+(d||0),y:b*Math.sin(e)+c*Math.cos(e)+(f||0)}}function getStandardAngle(b,c,e,d){return Math.atan2(c-(d||0),b-(e||0)).toDegrees().cleanAngle()}function getDistance(b,c,e,d){return Math.sqrt(Math.pow(b-e,2)+Math.pow(c-d,2))}function rand(b,c){return Math.floor(Math.random()*(c-b))+b}function forEach(b,c,e,d){console.log("called forEach");for(var f in b)b.hasOwnProperty(f)&&c(b[f],e,d)}
function randomHexCode(){console.log("called randomHexCode");return"#000000".replace(/0/g,function(){return(~~(16*Math.random())).toString(16)})}function getFileExtension(b){-1!==b.indexOf("?")&&(b=b.substr(0,b.indexOf("?")));if(b)return b.substr((~-b.lastIndexOf(".")>>>0)+2);console.warn("No file name provided")}
var loadFile=function(b,c){var e=0,d=new Image;return function(b){var g,k=getFileExtension(b).toLowerCase();switch(k){case "":return;case "js":case "json":g=document.createElement("script");g.setAttribute("type","text/javascript");g.setAttribute("src",b);break;case "css":g=document.createElement("link");g.setAttribute("rel","stylesheet");g.setAttribute("type","text/css");g.setAttribute("href",b);break;case "jpg":case "jpeg":case "png":case "gif":d.src=b;break;default:console.warn("This file type is not supported: "+
k);return}$("head").append(g);c&&console.log("Loaded file: "+b);e++}}();function hexAverage(){console.log("called a function that is on the chopping block");var b=Array.prototype.slice.call(arguments);return b.reduce(function(b,e){return e.replace(/^#/,"").match(/.{2}/g).map(function(d,e){return b[e]+parseInt(d,16)})},[0,0,0]).reduce(function(c,e){var d=Math.floor(e/b.length).toString(16);2>d.length&&(d="0"+d);return c+d},"#")}
function arrayifyArguments(b){for(var c=[],e=0;e<b.length;e++)c.push(b[e]);return c}function updateSome(){var b=arrayifyArguments(arguments);b.splice(0,0,!0);return jQuery.extend.apply({},b)}
var generatePushID=function(){var b=0,c=[];return function(){var e=(new Date).getTime(),d=e===b;b=e;for(var f=Array(8),g=7;0<=g;g--)f[g]="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(e%64),e=Math.floor(e/64);if(0!==e)throw Error("We should have converted the entire timestamp.");e=f.join("");if(d){for(g=11;0<=g&&63===c[g];g--)c[g]=0;c[g]++}else for(g=0;12>g;g++)c[g]=Math.floor(64*Math.random());for(g=0;12>g;g++)e+="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(c[g]);
if(20!=e.length)throw Error("Length should be 20.");return e}}();function doPolygonsIntersect(b,c){var e=[b,c],d,f,g,k,m,h,n,q;for(k=0;k<e.length;k++){var l=e[k];for(m=0;m<l.length;m++){d=l[m];f=l[(m+1)%l.length];var p=f.y-d.y,r=d.x-f.x;d=f=void 0;for(h=0;h<b.length;h++){g=p*b[h].x+r*b[h].y;if(!d||g<d)d=g;if(!f||g>f)f=g}n=q=void 0;for(h=0;h<c.length;h++){g=p*c[h].x+r*c[h].y;if(!n||g<n)n=g;if(!q||g>q)q=g}if(f<n||q<d)return!1}}return!0}
Array.prototype.toPolygonPathForm=function(b,c,e){var d=[];b||(b=[0,0]);c||(c=1);e||(e=0);for(var f=0;f<this.length;f++)d[f]=rotatePoint(this[f][0]*c,this[f][1]*c,e,b[0],b[1]);return d};
function clone(b,c){console.log("called a function that is on the chopping block");c||(c=3);switch(c){case 1:return JSON.parse(JSON.stringify(a));case 2:return jQuery.extend(!0,{},b);case 3:var e;if(null==b||"object"!=typeof b)return b;if(b instanceof Date)return e=new Date,e.setTime(b.getTime()),e;if(b instanceof Array){e=[];for(var d=0,f=b.length;d<f;d++)e[d]=clone(b[d]);return e}if(b instanceof Object){e={};for(d in b)b.hasOwnProperty(d)&&(e[d]=clone(b[d]));return e}throw Error("Unable to copy obj! Its type isn't supported.");
default:console.warn("Something bad happened")}}
function clone(b){if(!b)return b;var c=[Number,String,Boolean],e;c.forEach(function(c){b instanceof c&&(e=c(b))});if("undefined"==typeof e)if("[object Array]"===Object.prototype.toString.call(b))e=[],b.forEach(function(b,c,d){e[c]=clone(b)});else if("object"==typeof b)if(b.nodeType&&"function"==typeof b.cloneNode)e=b.cloneNode(!0);else if(b.prototype)e=b;else if(b instanceof Date)e=new Date(b);else{e={};for(var d in b)e[d]=clone(b[d])}else e=b;return e}
function occurrences(b,c,e){console.log("called a function that is on the chopping block");b+="";c+="";if(0>=c.length)return b.length+1;var d=0,f=0;for(e=e?1:c.length;;)if(f=b.indexOf(c,f),0<=f)++d,f+=e;else break;return d}function scrollTo(b,c){$("html, body").animate({scrollTop:$("#"+b).offset().top},c||2E3)}function isReallyNaN(b){return b!==b}
var QueryURL=function(){for(var b={},c=window.location.search.substring(1).split("&"),e=0;e<c.length;e++){var d=c[e].split("=");if("undefined"===typeof b[d[0]])b[d[0]]=decodeURIComponent(d[1]);else if("string"===typeof b[d[0]]){var f=[b[d[0]],decodeURIComponent(d[1])];b[d[0]]=f}else b[d[0]].push(decodeURIComponent(d[1]))}return b}();
function projectile(){return updateSome(new displayObject,{"class":"projectile",appearance:{sizeScale:{2:.2*variables.sizeScale}},gamePlay:{damage:40,speed:20,ranged:!0,damageType:"generic",hasDied:[0,!1],HP:100},minimalToRender:{gamePlay:{damage:!0,HP:!0,speed:!0},physics:{velocity:!0}},die:function(){var b=this.gamePlay,c=variables;b.hasDied[0]++;b.hasDied[1]||(b.hasDied[1]=c.timeStamp);if(!this.deathEffect())return this.minimalToRender.gamePlay.hasDied=!0,this.save(),!1;this.erase();this.isOwner()&&
!b.diedAwhileAgo?b.diedAwhileAgo=c.timeStamp:(delete c.interactingObjects[this.uid],objectsRef.child(this.uid).remove())},leaveArena:function(){return!0},gameCycle:function(){var b=this.physics,c=this.appearance.position;this.gamePlay.HP--;this.cycleEffect();c[0]+=b.velocity[0];c[1]-=b.velocity[1];this.isOwner()&&0===variables.timeStamp%variables.projectileSaveFrequency&&this.save()},collideWith:function(b){switch(b["class"]){case "userObject":case "robot":b=this.appearance.position,"OnContactEffect"!==
this.name&&functions.objectFactory("OnContactEffect",{appearance:{position:b}},{save:!0})}this.die()},cycleEffect:function(){var b=this.physics;this.appearance.rotate=getStandardAngle(b.velocity[0],-1*b.velocity[1])},deathEffect:function(){return!0}})}function Shotgun(){return updateSome(new weapon,{name:"Shotgun",gamePlay:{launches:ShotgunBullet,rateOfFire:50,spread:18,launchCount:4,speedMultiplier:.9},appearance:{shape:["v2.1",{src:"/g/assets/images/weapons/shotgun.png"}]}})}
function GrenadeLauncher(){return updateSome(new weapon,{name:"GrenadeLauncher",gamePlay:{launches:Explosive,rateOfFire:60},appearance:{shape:["v2.1",{src:"/g/assets/images/projectiles/missle-gray2.png"}]}})}function Pistol(){return updateSome(new weapon,{name:"Pistol",gamePlay:{launches:Bullet,rateOfFire:20},appearance:{shape:["v2.1",{src:"/g/assets/images/projectiles/missle-gray1.png"}]}})}
function Sword(){return updateSome(new weapon,{name:"Sword",gamePlay:{launches:Melee,launchCount:4,spread:65,rateOfFire:12},appearance:{shape:["v2.1",{src:"/g/assets/images/weapons/Arthas_sword.png"}]}})}function LittleSister(){return updateSome(new weapon,{name:"LittleSister",gamePlay:{launches:SisterShell,rateOfFire:7},appearance:{shape:["v2.1",{src:"/g/assets/images/weapons/Type-31_Rifle.png"}]}})}
function Sniper(){return updateSome(new weapon,{name:"Sniper",gamePlay:{launches:Bullet,rateOfFire:20,speedMultiplier:1.5,damageMultiplier:3.5},appearance:{shape:["v2.1",{src:"/g/assets/images/weapons/pulse_rifle.png"}]}})}function TestWeapon(){return updateSome(new weapon,{name:"TestWeapon",gamePlay:{launches:TestProjectile,rateOfFire:12,speed:10},appearance:{shape:["v2.1",{src:"/g/assets/images/weapons/purple_dominator.png"}]}})}
function Lazer(){return updateSome(new weapon,{name:"Lazer",gamePlay:{launches:LazerBeam,rateOfFire:20,speed:50},appearance:{shape:["v2.1",{src:"/g/assets/images/weapons/kraad.png"}]}})}
function userObject(){return updateSome(new displayObject,{"class":"userObject",appearance:{sizeScale:{0:.8*variables.sizeScale,1:1.3*variables.sizeScale,2:1*variables.sizeScale}},gamePlay:{buttonMapping:{cw:82,cw_last_pressed:-1,dn:[40,83],fi:32,lt:[37,65],rt:[39,68],sb:81,ss:69,up:[38,87],sl:90,sr:67},HP:1500,maxHP:2E3,resizeSpeed:15,rotateSpeed:5,shieldRegen:5,shieldBurnOut:125,currentShieldBurnOut:0,maxShields:300,sideThrusting:{rate:1,max:16,extraSpeed:3,extraAcceleration:30,current:0,displacement:0,
burned:!1,controlling:!1},speed:15,damageMultiplier:1,projectileSpeed:1,weaponKeywords:["Sniper","Sword","GrenadeLauncher","TestWeapon","Lazer"]},physics:{mass:300,userVelocity:[0,0]},user:{keyboard:{},level:0,mouse:{x:0,y:0,down:!1},name:"Johnny Appleseed",stats:{dateCreated:firebase.database.ServerValue.TIMESTAMP,lastLogin:firebase.database.ServerValue.TIMESTAMP,stats:"other stats",totalTimePlayed:0},upgrades:{damageBoost:1},username:"J. Appleseed",xp:0,xpNeeded:4E3,publicProfileImg:"/g/assets/images/defaultProfilePic.png",
availableToPublic:!0,summary:function(){return"This is a very fast ship with moderate sheilds, but damage to destroy all enemies forever!"}},minimalToRender:{gamePlay:{shields:!0,weaponKeywords:!0,HP:!0},physics:{velocity:!0},user:{publicProfileImg:!0,username:!0}},leaveArena:function(b,c){var e=this.physics,d=this.appearance.position,f=variables.canvas;switch(b){case "left":case "right":e.velocity[0]=0;d[0]="left"===b?c[b]:f.width-c[b];break;case "top":case "bottom":e.velocity[1]=0,d[1]="top"===
b?c[b]:f.height-c[b]}this.physics=e;this.appearance.position=d},gameCycle:function(){this.applyGameLogic();this.isOwner()&&0===variables.timeStamp%variables.userSaveFrequency&&this.save()},applyGameLogic:function(){var b=variables,c=this.appearance,e=c.position,d=this.gamePlay,f=d.weapons,g=this.physics,k=this.isPressed("up"),m=this.isPressed("dn"),h=this.isPressed("lt"),n=this.isPressed("rt"),q=this.isPressed("sr"),l=this.isPressed("sl"),p=0,r;this.isOwner()&&(1===q+l||d.sideThrusting.controlling?
(f=d.sideThrusting,1!==q+l||f.burned?(f.current-=1/f.rate,r=1/f.rate,0<f.displacement&&(r*=-1),f.displacement+=r):(++f.current,g.userVelocity=[f.extraSpeed*d.speed*(q-l),(c.rotate+90).toRadians()].toCartesian(),f.displacement+=q-l),f.current>=f.max?f.burned=!0:0===f.current?(f.burned&&(f.burned=!1),g.velocity=[0,0],g.userVelocity=[0,0]):p=f.current/f.max/2*b.accelerationConst*((f.max-f.current)/f.max)/(g.mass/f.extraAcceleration),f.controlling=0!==f.current?!0:!1):(1===h+n&&(c.rotate=h?c.rotate-d.rotateSpeed:
c.rotate+d.rotateSpeed),0===(c.rotate=c.rotate.cleanAngle())%90&&++c.rotate,g.userVelocity=[d.speed*(k-m)*(.5*m||1),c.rotate.toRadians()].toCartesian(),p=this.isPressed("ss"),q=this.isPressed("sb"),1===p+q&&(c=c.sizeScale,l=(c[1]-c[0])/d.resizeSpeed,p&&(l*=-1),p&&c[0]>=c[2]||q&&c[1]<=c[2]||(p=d.HP/d.maxHP,c[2]+=l,d.maxHP-=25*l,d.maxShields-=25*l,d.shieldRegen-=.04*l*1.1,d.speed-=.16*l,d.damageMultiplier+=.04*l,d.HP=p*d.maxHP)),f[0].gamePlay.cooldown--,this.isPressed("fi")&&0>=f[0].gamePlay.cooldown&&
this.fireWeapon(),this.isPressed("cw")&&d.cw_last_pressed!==(r=this.isPressed("cw",!0))&&(d.cw_last_pressed=r,this.changeWeapon()),p=b.accelerationConst/g.mass),g.velocity[0]+=p*(g.userVelocity[0]-g.velocity[0]),g.velocity[1]+=p*(g.userVelocity[1]-g.velocity[1]));this.isOwner()&&0>=d.currentShieldBurnOut--&&(d.shields+=d.shieldRegen);d.shields=Math.min(d.shields,d.maxShields);d.HP=Math.min(d.HP,d.maxHP);e[0]+=g.velocity[0];e[1]+=g.velocity[1]},isPressed:function(b,c){return functions.isPressed(this.gamePlay.buttonMapping[b],
c)},draw:function(){functions.renderObject(this.appearance);functions.renderObject(updateSome(this.gamePlay.weapons[0],{appearance:{position:this.appearance.position,rotate:this.appearance.rotate}}).appearance);var b=variables.display,c=b.HPbar,e=variables.context,d=this.appearance.position,f=c.height,g=c.width,k=[],m,h=this.gamePlay;m=h.sideThrusting;e.setFontSize(f+"px");k.push({present:c.HPcolor.present,absent:c.HPcolor.absent,percent:h.HP/h.maxHP,text:Math.round(h.HP)+" / "+Math.round(h.maxHP)});
var n;n=0<h.currentShieldBurnOut&&this.isOwner()?"Burned out for: "+Math.ceil(h.currentShieldBurnOut/10):n=Math.round(h.shields)+" / "+Math.round(h.maxShields);k.push({present:c.shieldColor.present,absent:c.shieldColor.absent,percent:h.shields/h.maxShields,text:n});this.isOwner()&&"userObject"===this["class"]&&(h=h.weapons[0],n=h.gamePlay,k.push({present:c.weaponColor.present,absent:c.weaponColor.absent,percent:(n.rateOfFire-n.cooldown.min(0))/n.rateOfFire,text:h.name}));0<m.current&&k.push({present:c.strifeColor.present,
absent:c.strifeColor.absent,percent:m.current/m.max,text:"Moving Sideways!",backwards:0>m.displacement});e.textAlign="start";for(h=0;h<k.length;h++)m=k[h],e.fillStyle=m.absent||"white",e.fillRect(d[0]-g/2,d[1]-c.y_offset-f*h,g,f),e.fillStyle=m.present||"black",m.backwards?(n=g*m.percent,e.fillRect(d[0]-g/2+(g-n),d[1]-c.y_offset-f*h,n,f)):e.fillRect(d[0]-g/2,d[1]-c.y_offset-f*h,g*m.percent,f),m.text&&(e.fillStyle=b.usernameColor,e.fillText(m.text,d[0]-g/2+c.left_pad,d[1]-c.y_offset-f*(h-1)-c.bottom_pad));
e.textAlign="center";e.fillText(this.user.username,d[0],d[1]-c.y_offset-f*k.length);f=new Image;b=b.profilePic;f.src=this.user.publicProfileImg;e.drawImage(f,d[0]+b.x_offset,d[1]-b.y_from_HPbar-c.y_offset,b.size,b.size)},erase:function(){functions.renderObject(this.appearance,!0);functions.renderObject(this.gamePlay.weapons[0].appearance,!0);var b=this.appearance.position,c=variables.display,e=c.HPbar,c=-1*Math.max(e.width/2,-1*c.profilePic.x_offset),d=5;this.isOwner()&&"userObject"===this["class"]&&
d++;d*=e.height;variables.context.clearRect(c+b[0]-1,b[1]-e.y_offset-(d-e.height)+1,-1*c+e.width/2+2,d+2)},fireWeapon:function(){var b={damage:this.gamePlay.damageMultiplier,speed:this.gamePlay.projectileSpeed};"robot"===this["class"]&&(b.immuneTo=[this.uid,"robot"]);this.gamePlay.weapons[0].fire(b)},changeWeapon:function(){var b=this.gamePlay,c=b.weapons,b=b.weaponKeywords;c.move(0,-1);b.move(0,-1);c[0].gamePlay.cooldown=c[0].gamePlay.rateOfFire;variables.activeUserGameServer.child("gamePlay/weaponKeywords/0").set(c[0].name)},
takeDamage:function(b){var c=this.gamePlay,e=c.HP,d=c.shields;this.isOwner()&&(b<=d&&0>=c.currentShieldBurnOut?d-=b:(d=0,0>=c.currentShieldBurnOut&&(c.currentShieldBurnOut=c.shieldBurnOut),e-=b-d),this.gamePlay.HP=e,this.gamePlay.shields=d)},collideWith:function(b){var c=[this.gamePlay.speed/this.physics.mass],e=this.appearance.position,d=b.appearance.position,f=b.gamePlay;switch(b["class"]){case "projectile":this.takeDamage(b.gamePlay.damage);break;case "userObject":case "robot":c[1]=getStandardAngle(e[0],
e[1],d[0],d[1]).toRadians();c=c.toCartesian();this.physics.velocity[0]+=c[0];this.physics.velocity[1]+=c[1];this.takeDamage(f.HP*f.damageMultiplier/variables.reduceRammingDmg);break;default:console.warn(b["class"],"unknown class of other object")}},die:function(){this.erase();this.isOwner()&&(functions.userMessage("You just died!","error"),this.respawn())},respawn:function(){var b=this.gamePlay,c=this.appearance.position;b.HP=b.maxHP;b.shields=b.maxShields;b.currentShieldBurnOut=0;this.appearance.rotate=
rand(0,360);c[0]=rand(0,variables.canvasSize[0]);c[1]=rand(0,variables.canvasSize[1])},onCompleteConstruction:function(){var b=this.gamePlay,c=b.weaponKeywords;b.weapons=[];for(var e in c)!1===isNaN(parseInt(e,10))&&(b.weapons[e]=functions.objectFactory(c[e]));b.HP=b.maxHP;b.shields=b.maxShields}})}
function displayObject(){return{uid:generatePushID(),name:"displayObject","class":"generic",gamePlay:{HP:1001,owner:variables.activeUser,immuneTo:["no-one"]},appearance:{shape:["v2.1",{src:"/g/assets/images/icons/missing.gif"}],rotate:0,sizeScale:{0:1,1:3*variables.sizeScale,2:1},position:variables.canvas?[rand(0,variables.canvas.width),rand(0,variables.canvas.height)]:[0,0]},physics:{mass:0,velocity:[0,0],hitBox:{simple:[-.5,.5,.5,-.5],corners:[[.5,.5],[.5,-.5],[-.5,-.5],[-.5,.5]],testPoints:[[1,
1],[1,-1],[-1,1],[-1,-1]]}},minimalToRender:{uid:!0,name:!0,gamePlay:{owner:!0,immuneTo:!0},appearance:{sizeScale:{2:!0},rotate:!0,position:!0}},leaveArena:function(b,c){console.log(this.name,"left the arena to the",b,"--\x3e Props:",c);return!0},gameCycle:function(){console.log(this.name,"fired a gameCycle")},draw:function(){functions.renderObject(this.appearance)},erase:function(){functions.renderObject(this.appearance,!0)},save:function(){this.isOwner()&&(variables.leaveGame||variables.singlePlayerMode||
objectsRef.update(function(b){var c={};c[b.uid]=functions.standardizeForFirebase(b);return c}(this)))},collideWith:function(b){console.log(this.name,"collided with",b.name)},onCompleteConstruction:function(){},isOwner:function(){return this.gamePlay.owner===variables.activeUser?!0:!1}}}
function OnContactEffect(){return updateSome(new projectile,{name:"OnContactEffect",gamePlay:{damage:0,HP:4},appearance:{shape:["v2.1",{src:"/g/assets/images/projectiles/on-contact-effect.png"}],sizeScale:{2:.4*variables.sizeScale}},minimalToRender:{appearance:!1,gamePlay:!1,physics:!1,user:!1},physics:{mass:10}})}
function Explosive(){return updateSome(new orb,{name:"Explosive",gamePlay:{damage:50,damageType:"explosive",HP:400,speed:7.2},appearance:{sizeScale:{2:.7*variables.sizeScale},shape:["v2.1",{src:"/g/assets/images/projectiles/orbs/circular-lazer-shot.png"}]},physics:{mass:30},leaveArena:function(b){var c=this.physics.velocity,e=this.appearance;switch(b){case "top":case "bottom":return!0;case "left":e.position[0]=variables.canvas.width-this.physics.hitBox.simple[1]*e.sizeScale[2]-1;break;case "right":c[0]*=
-2}},deathEffect:function(){var b=this.gamePlay,c=variables;if(b.hasDied[1]&&10<c.timeStamp-b.hasDied[1])return!0;this.gamePlay.HP=11;this.physics.velocity[0]/=2;this.physics.velocity[1]/=2;this.appearance.sizeScale[2]*=1.1;this.minimalToRender.appearance.sizeScale[2]=!0;return!1}})}
function ShotgunBullet(){return updateSome(new Bullet,{name:"ShotgunBullet",gamePlay:{damage:12,HP:150},appearance:{shape:["v2.1",{src:"/g/assets/images/projectiles/blue-lazer.png"}]},leaveArena:function(){return!0}})}function SisterShell(){return updateSome(new orb,{name:"SisterShell",gamePlay:{damage:45,HP:25,speed:18},appearance:{shape:["v2.1",{src:"/g/assets/images/projectiles/orbs/Dream_Smoke_Ball_Sprite.png"}]}})}
function LazerBeam(){return updateSome(new projectile,{name:"LazerBeam",gamePlay:{damage:120,damageType:"energy",speed:50},appearance:{shape:["v2.1",{src:"/g/assets/images/projectiles/solid-red-lazer.jpg"}],sizeScale:{2:.9*variables.sizeScale}},physics:{mass:20},deathEffect:function(){var b=this.gamePlay,c=variables,e=this.appearance;if(b.hasDied[1]&&10<c.timeStamp-b.hasDied[1])return!0;b.HP=22;e.shape[1].src="/g/assets/images/projectiles/blue-lazer.png";e.sizeScale[2]/=4;b.speed*=3;b.damageMultiplier*=
3;this.leaveArena=function(b){var c=this.physics.velocity,e=Math.abs(c[0]),k=Math.abs(c[1]);switch(b){case "left":c[0]=e;break;case "right":c[0]=0-e;break;case "top":c[1]=0-k;break;case "bottom":c[1]=k}return!1};return!1}})}
function orb(){return updateSome(new projectile,{appearance:{spinDirection:rand(0,2)?1:-1,spinSpeed:rand(3,7),sizeScale:{2:.15*variables.sizeScale}},gamePlay:{speed:2,damageType:"ranged"},physics:{mass:5},cycleEffect:function(){var b=this.appearance;b.rotate+=b.spinDirection*b.spinSpeed}})}
function Melee(){return updateSome(new projectile,{name:"Melee",gamePlay:{damage:65,ranged:!1,damageType:"melee",HP:10,speed:40},appearance:{shape:["v2.1",{src:"/g/assets/images/projectiles/blue-sword-arc.png"}],sizeScale:{2:1.2*variables.sizeScale}},physics:{mass:60}})}
function Bullet(){return updateSome(new projectile,{name:"Bullet",gamePlay:{damage:20,HP:150,speed:20},appearance:{shape:["v2.1",{src:"/g/assets/images/projectiles/8bit-green.png"}]},physics:{mass:10},leaveArena:function(b){var c=this.physics.velocity;switch(b){case "top":c[1]=0-Math.abs(c[1]);break;case "bottom":c[1]=Math.abs(c[1]);break;case "left":case "right":return!0}}})}
function TestProjectile(){return updateSome(new projectile,{name:"TestProjectile",gamePlay:{damage:100,damageType:"melee",HP:250,speed:10},appearance:{shape:["v2.1",{src:"/g/assets/images/projectiles/missle-darkgray2.png"}],sizeScale:{2:.85*variables.sizeScale}},physics:{mass:60}})}
function weapon(){return updateSome(new displayObject,{"class":"weapon",gamePlay:{spread:0,launchCount:1,launches:Bullet,rateOfFire:30,cooldown:0,speedMultiplier:1,damageMultiplier:1,rangeMultiplier:1},appearance:{sizeScale:{2:.4*variables.sizeScale}},fire:function(b){this.gamePlay.cooldown=this.gamePlay.rateOfFire;var c,e=this.appearance,d=this.gamePlay,f=[];c=d.launchCount;d=d.spread;if(1===c)f=[d];else{f[c-1]=0;f[0]=d;for(var g=1;g<c-1;g++)f[g]=d/(c-1)*g}for(g=0;g<f.length;g++)c=new this.gamePlay.launches,
c.gamePlay.damage=c.gamePlay.damage*(b.damage||1)*this.gamePlay.damageMultiplier,c.gamePlay.speed=c.gamePlay.speed*(b.speed||1)*this.gamePlay.speedMultiplier,c.gamePlay.HP=c.gamePlay.HP*(b.range||1)*this.gamePlay.rangeMultiplier,c=updateSome(c,{appearance:{position:e.position,rotate:e.rotate},gamePlay:{immuneTo:b.immuneTo||[variables.activeUser]},physics:{velocity:[c.gamePlay.speed,-1*(e.rotate+(f[g]-d/2)).toRadians()].toCartesian()}}),variables.interactingObjects[c.uid]=c,c.save()}})}
var fromPHP={},database=mainFirebase.child("users"),gameServer=mainFirebase.child("gameServer/chrome"),whitelistRef=gameServer.child("whiteList"),objectsRef=gameServer.child("interactingObjects/active"),pingsRef=gameServer.child("lastPings"),messageRef=gameServer.child("messages"),authObject={serverPassword:"big5",canvas:"canvas",ownerLogin:function(){var b=!1;if(this.isOwnerLoggedIn())b=!0;else{var c=prompt("What is the owner password?");c===this.serverPassword&&(Cookies.set("ServerPassword",c,{expires:7}),
b=!0)}return b?(this.onOwnerAuthStateChanged(),!0):!1},isOwnerLoggedIn:function(){return Cookies.get("ServerPassword")===this.serverPassword?!0:!1},ownerLogout:function(){Cookies.remove("ServerPassword");functions.userMessage("Thanks for preserving the integrity of our special content","success",2E3);this.onOwnerAuthStateChanged();return!1},onOwnerAuthStateChanged:function(){authObject.isOwnerLoggedIn()?(functions.userMessage("You are an owner","success",2E3),$("#ownerButton").html("Logout as owner").attr("onclick",
"authObject.ownerLogout()")):$("#ownerButton").html("Login as owner").attr("onclick","authObject.ownerLogin()")},login:function(b){b.app&&(b=new firebase.auth.GoogleAuthProvider,firebase.auth().signInWithPopup(b))},logout:function(){firebase.auth().signOut()}};$(document).ready(authObject.onOwnerAuthStateChanged);
firebase.auth().onAuthStateChanged(function(b){var c=$("#login"),e=$("#logout");b?(b.displayName||(b.displayName=b.email.substr(0,b.email.indexOf("@"))),authObject.authData=b,console.log("Authenticated successfully with payload:",b),c.html("Logged in as "+b.displayName).prop("disabled","true"),e.removeAttr("disabled")):(console.log("Signed out :("),c.html("Login with Google").removeAttr("disabled"),e.prop("disabled","true"),authObject.authData=!1)});
variables={interactingObjects:{},timeStamp:0,canvasID:"canvas",activeUser:"generic",leaveGame:!1,singlePlayerMode:!1,debugFlags:{showFilesLoaded:!0},display:{HPbar:{HPcolor:{},shieldColor:{},weaponColor:{}},usernameColor:"#fff"}};
function initiateWorld(){variables.canvas=document.getElementById(variables.canvasID);variables.context=variables.canvas.getContext("2d");authObject.authData&&(variables.activeUser=authObject.authData.uid);var b=function(b){switch(b){case "canvasSize":variables.canvas.width=variables.canvasSize[0],variables.canvas.height=variables.canvasSize[1]}};gameServer.child("gameVariables").on("child_added",function(c){variables[c.key]=c.val();b(c.key)});gameServer.child("gameVariables").on("child_changed",
function(c){variables[c.key]=c.val();b(c.key)});init()}
function listenToObjectsRef(){objectsRef.on("child_added",function(b){var c=functions.objectFactory(b.val().name,b.val(),{save:!0});if(b.key!==variables.activeUser)b.ref.on("child_added",function(b){var d=c[b.key];updateSome(d,b.val());b.ref.on("child_changed",function(b){var e=d[b.key]=b.val();"weaponKeywords"===b.key&&(c.gamePlay.weapons[0]=functions.objectFactory(e[0]))})})});objectsRef.on("child_removed",function(b){delete variables.interactingObjects[b.key];b.ref.off()})}
var serverHelper={resizeCanvas:function(b){gameServer.child("gameVariables/canvasSize").update(function(){var c=document.getElementById(b.target),e=c.querySelector("#width"),c=c.querySelector("#height"),d;d=b.auto?[window.innerWidth-2,window.innerHeight-2]:b.target?[parseInt(e.value,10),parseInt(c.value,10)]:[b.width,b.height];var f={};0<d[0]&&!isNaN(d[0])&&(f[0]=d[0],e.value=d[0]);0<d[1]&&!isNaN(d[1])&&(f[1]=d[1],c.value=d[1]);return f}())}};
function init(){authObject.isOwnerLoggedIn()||authObject.ownerLogin()?($("#control_buttons > #start").html("Server started"),variables.activeUser="server",messageRef.on("child_added",function(b){var c=b.val();if("server"===c.target)switch(c.action){case "join":whitelistRef.child(c.origin).set(!0),variables.debugFlags.showStagesPerformed&&console.log("added "+c.origin+" to the game")}c.target===variables.activeUser&&b.ref.remove()}),setTimeout(cleanUsers,6E4)):functions.userMessage("Sorry, you can't start a server",
"error")}function cleanUsers(b){console.log("cleaning users");pingsRef.child(variables.activeUser).set(firebase.database.ServerValue.TIMESTAMP).then(function(b){pingsRef.once("value").then(function(b){b=b.val();for(var c in b)b.hasOwnProperty(c)&&b!==variables.activeUser&&b.server-b[c]>variables.pingAllowance+variables.pingFrequency&&removeUser(c)})});b||setTimeout(cleanUsers,variables.cleanUsersFrequency)}
function removeUser(b){console.log("Removing",b);whitelistRef.child(b).remove();objectsRef.child(b).remove();console.log("removed:",b)}function Allegiance(){return updateSome(new userObject,{name:"Allegiance",appearance:{shape:["v2.1",{src:"/g/assets/images/sprites/5concepts-purple.png"}],displayName:"EFS Allegiance"},gamePlay:{maxHP:3200,maxShields:265,shieldRegen:1.7,damageMultiplier:1.3},physics:{mass:175}})}
function Vigil(){return updateSome(new userObject,{name:"Vigil",appearance:{shape:["v2.1",{src:"/g/assets/images/sprites/5concepts-red.png"}],displayName:"EFS Vigil"},gamePlay:{maxHP:1400,resizeSpeed:25,shieldRegen:2.8,maxShields:1E3,speed:12,weaponKeywords:["Sword","Sniper"]},physics:{mass:90}})}
function Basilisk(){return updateSome(new userObject,{name:"Basilisk",appearance:{shape:["v2.1",{src:"/g/assets/images/sprites/5c2-orange.png"}],displayName:"CSS Basilisk"},gamePlay:{maxHP:2300,resizeSpeed:20,shieldRegen:2.4,maxShields:500,speed:13,weaponKeywords:["GrenadeLauncher","Pistol","Lazer"],damageMultiplier:1.1},physics:{mass:120}})}
function Pathfinder(){return updateSome(new userObject,{name:"Pathfinder",appearance:{shape:["v2.1",{src:"/g/assets/images/sprites/5concepts-orange.png"}],displayName:"HMS Pathfinder"},gamePlay:{maxHP:2700,shieldRegen:2.1,maxShields:350,damageMultiplier:1.6},physics:{mass:220}})}
function Scorpio(){return updateSome(new userObject,{name:"Scorpio",appearance:{shape:["v2.1",{src:"/g/assets/images/sprites/aliensh.png"}],displayName:"JFF Scorpio"},gamePlay:{maxHP:2700,resizeSpeed:20,rotateSpeed:6.5,shieldRegen:6,shieldBurnOut:90,maxShields:3500,speed:19,damageMultiplier:4,weaponKeywords:"GrenadeLauncher Pistol Lazer Shotgun TestWeapon Sword LittleSister".split(" ")},physics:{mass:60},user:{availableToPublic:!1}})}
function Trident(){return updateSome(new userObject,{name:"Trident",appearance:{shape:["v2.1",{src:"/g/assets/images/sprites/5c2-teal.png"}],displayName:"HSV Trident"},gamePlay:{maxHP:5E3,shieldRegen:2,maxShields:1200,speed:9.75,rotateSpeed:3,damageMultiplier:3},physics:{mass:600}})}
function Tempest(){return updateSome(new userObject,{name:"Tempest",appearance:{shape:["v2.1",{src:"/g/assets/images/sprites/5c2-purple.png"}],displayName:"EAS Tempest"},gamePlay:{maxHP:3330,shieldRegen:2,maxShields:300,damageMultiplier:2},physics:{mass:300}})}
function Starseeker(){return updateSome(new userObject,{name:"Starseeker",appearance:{shape:["v2.1",{src:"/g/assets/images/sprites/5c2-blue.png"}],displayName:"UES Starseeker"},gamePlay:{maxHP:3E3,shieldRegen:2,maxShields:300,damageMultiplier:1.9},physics:{mass:300}})}
function Aden(){return updateSome(new userObject,{name:"Aden",appearance:{shape:["v2.1",{src:"/g/assets/images/sprites/5concepts-blue.png"}],displayName:"FTLS Gulf of Aden"},gamePlay:{maxShields:700,maxHP:400,shieldRegen:2.9,speed:16,weaponKeywords:["Sword","TestWeapon"],rotateSpeed:8,damageMultiplier:1.5},physics:{mass:100}})};
</script>
<style type='text/css'>body{margin:0;padding:0;overflow:hidden;background:url('/g/assets/images/background.jpg');background-position-x:center;position:relative;height:100vh}canvas{border:6px solid #0e1f5b;background:rgba(225,225,225,0.4)}.centerAll{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%)}.userMessage{font-family:Arial,Helvetica,sans-serif;font-size:13px;border:1px solid;padding:15px 10px 15px 50px;background-repeat:no-repeat;background-position:10px center;position:fixed;bottom:5px;right:5px;z-index:1;display:none}.info{color:#00529B;background-color:#BDE5F8;background-image:url('/g/assets/images/icons/blue-i.png')}
.success{color:#4F8A10;background-color:#DFF2BF;background-image:url('/g/assets/images/icons/green-check.png')}.warning{color:#9F6000;background-color:#FEEFB3;background-image:url('/g/assets/images/icons/yellow-exclamation.png')}.error{color:#D8000C;background-color:#FFBABA;background-image:url('/g/assets/images/icons/red-x.png')}.validation{color:#D63301;background-color:#FFCCBA;background-image:url('/g/assets/images/icons/blue-exclamation.png')}#server canvas{border-width:5px}#server #canvasSize{display:inline}#server #canvasSize input{width:50px}#server #control_buttons{position:fixed;width:100%;background:rgba(12, 11, 107, 0.37);z-index:1}</style>